const CAPTURE = "x"
const CAPTURE_PROMOTE = "C"
const CHECK = "+"
const CHECKMATE = "#"
const KINGSIDE_CASTLE = "0-0"
const QUEENSIDE_CASTLE = "0-0-0"
const MOVE = ""
const MOVE_PROMOTE = "Q"
const DRAW_OFFER = "="

export {
  CAPTURE,
  CAPTURE_PROMOTE,
  CHECK,
  CHECKMATE,
  DRAW_OFFER,
  KINGSIDE_CASTLE,
  MOVE,
  MOVE_PROMOTE,
  QUEENSIDE_CASTLE,
}
